set Pathname="C:\Program Files (x86)\NCSOFT\BnS"
cd /d %Pathname%
del bin\NCTalk.exe
del contents\bns\CookedPC\00009108.upk
del contents\bns\CookedPC\00009368.upk
del contents\bns\CookedPC\00015590.upk
del contents\bns\CookedPC\00015646.upk
del contents\bns\CookedPC\00015671.upk
del contents\bns\CookedPC\00016309.upk
del contents\bns\CookedPC\00016310.upk
del contents\bns\CookedPC\00016311.upk
del contents\bns\CookedPC\00016316.upk
del contents\bns\CookedPC\00016317.upk
del contents\bns\CookedPC\00016318.upk
del contents\bns\CookedPC\00016319.upk
del contents\bns\CookedPC\00016320.upk
del contents\bns\CookedPC\00016321.upk
del contents\bns\CookedPC\00016322.upk
del contents\bns\CookedPC\00016323.upk
del contents\bns\CookedPC\00016324.upk
del contents\bns\CookedPC\00016325.upk
del contents\bns\CookedPC\00016326.upk
del contents\bns\CookedPC\00016327.upk
del contents\bns\CookedPC\00016328.upk
del contents\bns\CookedPC\00016329.upk
del contents\bns\CookedPC\00016407.upk
del contents\bns\CookedPC\00016720.upk
del contents\bns\CookedPC\00016721.upk
del contents\bns\CookedPC\00016727.upk
del contents\bns\CookedPC\00016947.upk
del contents\bns\CookedPC\00017462.upk
del contents\bns\CookedPC\00017465.upk
del contents\bns\CookedPC\00017466.upk
del contents\bns\CookedPC\00017664.upk
del contents\bns\CookedPC\00017775.upk
del contents\bns\CookedPC\00017776.upk
del contents\bns\CookedPC\00017777.upk
del contents\bns\CookedPC\00017778.upk
del contents\bns\CookedPC\00017832.upk
del contents\bns\CookedPC\00017833.upk
del contents\bns\CookedPC\00017834.upk
del contents\bns\CookedPC\00017835.upk
del contents\bns\CookedPC\00018099.upk
del contents\bns\CookedPC\00018100.upk
del contents\bns\CookedPC\00018292.upk
del contents\bns\CookedPC\00019222.upk
del contents\bns\CookedPC\00019396.upk
del contents\bns\CookedPC\00020255.upk
del contents\bns\CookedPC\00028079.upk
del contents\bns\CookedPC\00028141.upk
del contents\bns\CookedPC\00029569.upk
del contents\bns\CookedPC\Daesamak_3001_Federation_0_0.upk
del contents\bns\CookedPC\Daesamak_3001_Federation_0_1.upk
del contents\bns\CookedPC\Daesamak_3001_Federation_1_0.upk
del contents\bns\CookedPC\Daesamak_3001_Federation_1_1.upk
del contents\bns\CookedPC\Daesamak_3001_FederationInfo.upk
del contents\bns\CookedPC\Daesamak_3002_Federation_0_0.upk
del contents\bns\CookedPC\Daesamak_3002_Federation_0_1.upk
del contents\bns\CookedPC\Daesamak_3002_Federation_1_0.upk
del contents\bns\CookedPC\Daesamak_3002_Federation_1_1.upk
del contents\bns\CookedPC\Daesamak_3002_FederationInfo.upk
del contents\bns\CookedPC\Daesamak_3003_Federation_0_0.upk
del contents\bns\CookedPC\Daesamak_3003_Federation_0_1.upk
del contents\bns\CookedPC\Daesamak_3003_Federation_1_0.upk
del contents\bns\CookedPC\Daesamak_3003_Federation_1_1.upk
del contents\bns\CookedPC\Daesamak_3003_FederationInfo.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_0_0.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_0_1.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_0_2.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_1_0.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_1_1.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_1_2.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_2_0.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_2_1.upk
del contents\bns\CookedPC\Daesamak_3004_Federation_2_2.upk
del contents\bns\CookedPC\Daesamak_3004_FederationInfo.upk
del contents\bns\CookedPC\house_1_Federation_0_0.upk
del contents\bns\CookedPC\house_1_FederationInfo.upk
del contents\bns\CookedPC\Labyrinth_I_VC_05bCinema.umap
del contents\bns\CookedPC\MusinTower_Hero_Federation_0_0.upk
del contents\bns\CookedPC\MusinTower_Hero_FederationInfo.upk
del contents\bns\CookedPC\NorthField_n_Federation_0_0.upk
del contents\bns\CookedPC\NorthField_n_Federation_0_1.upk
del contents\bns\CookedPC\NorthField_n_Federation_0_2.upk
del contents\bns\CookedPC\NorthField_n_Federation_1_0.upk
del contents\bns\CookedPC\NorthField_n_Federation_1_1.upk
del contents\bns\CookedPC\NorthField_n_Federation_1_2.upk
del contents\bns\CookedPC\NorthField_n_Federation_2_0.upk
del contents\bns\CookedPC\NorthField_n_Federation_2_1.upk
del contents\bns\CookedPC\NorthField_n_Federation_2_2.upk
del contents\bns\CookedPC\NorthField_n_Federation_3_0.upk
del contents\bns\CookedPC\NorthField_n_FederationInfo.upk
del contents\bns\CookedPC\NorthField_s_Federation_0_0.upk
del contents\bns\CookedPC\NorthField_s_Federation_0_1.upk
del contents\bns\CookedPC\NorthField_s_Federation_0_2.upk
del contents\bns\CookedPC\NorthField_s_Federation_1_0.upk
del contents\bns\CookedPC\NorthField_s_Federation_1_1.upk
del contents\bns\CookedPC\NorthField_s_Federation_1_2.upk
del contents\bns\CookedPC\NorthField_s_Federation_2_0.upk
del contents\bns\CookedPC\NorthField_s_Federation_2_1.upk
del contents\bns\CookedPC\NorthField_s_Federation_2_2.upk
del contents\bns\CookedPC\NorthField_s_Federation_3_0.upk
del contents\bns\CookedPC\NorthField_s_Federation_3_1.upk
del contents\bns\CookedPC\NorthField_s_Federation_3_2.upk
del contents\bns\CookedPC\NorthField_s_FederationInfo.upk
del contents\bns\CookedPC\NPC_BC_BooNong.upk
del contents\bns\CookedPC\NPC_BC_BooNong_1.upk
del contents\bns\CookedPC\NPC_BC_BooNong_2.upk
del contents\bns\CookedPC\NPC_BC_BooNong_3.upk
del contents\bns\CookedPC\NPC_BC_Booyudo.upk
del contents\bns\CookedPC\NPC_BC_Def.upk
del contents\bns\CookedPC\NPC_BC_Def_1.upk
del contents\bns\CookedPC\NPC_BC_Def_2.upk
del contents\bns\CookedPC\NPC_BC_Def_3.upk
del contents\bns\CookedPC\NPC_BC_Epic.upk
del contents\bns\CookedPC\NPC_BC_Epic_1.upk
del contents\bns\CookedPC\NPC_BC_Epic_2.upk
del contents\bns\CookedPC\NPC_BC_Epic_3.upk
del contents\bns\CookedPC\NPC_BC_GangRyu.upk
del contents\bns\CookedPC\NPC_BC_GangRyu_1.upk
del contents\bns\CookedPC\NPC_BC_GangRyu_2.upk
del contents\bns\CookedPC\NPC_BC_SeolSan.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_1.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_2.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_3.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_4.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_5.upk
del contents\bns\CookedPC\NPC_BC_SeolSan_6.upk
del contents\bns\CookedPC\NPC_BCRe_Baram.upk
del contents\bns\CookedPC\NPC_BCRe_Def_1.upk
del contents\bns\CookedPC\NPC_BCRe_Def_3.upk
del contents\bns\CookedPC\NPC_BCRe_Def_4.upk
del contents\bns\CookedPC\NPC_BCRe_Def_5.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_1.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_1_1.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_2.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_2_1.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_2_2.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_3.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_4.upk
del contents\bns\CookedPC\NPC_BCRe_Epic_4_1.upk
del contents\bns\CookedPC\NPC_BCRe_GangRyu.upk
del contents\bns\CookedPC\NPC_Epic_Sixth.upk
del contents\bns\CookedPC\NPC_InsDun_Dungeun.upk
del contents\bns\CookedPC\NPC_InsDun_Dungeun_1.upk
del contents\bns\CookedPC\NPC_InsDun_Dungeun_2.upk
del contents\bns\CookedPC\NPC_InsDun_Dungeun_3.upk
del contents\bns\CookedPC\NPC_MS_Def.upk
del contents\bns\CookedPC\NPC_MS_Musin.upk
del contents\bns\CookedPC\NPC_PVP_Arena.upk
del contents\bns\CookedPC\NPC_PvP_Def.upk
del contents\bns\CookedPC\PaCheonSeong_Area02_Federation_0_0.upk
del contents\bns\CookedPC\PaCheonSeong_Area02_Federation_0_1.upk
del contents\bns\CookedPC\Suwal_4001_Federation_0_0.upk
del contents\bns\CookedPC\Suwal_4001_Federation_0_1.upk
del contents\bns\CookedPC\Suwal_4001_Federation_0_2.upk
del contents\bns\CookedPC\Suwal_4001_Federation_1_0.upk
del contents\bns\CookedPC\Suwal_4001_Federation_1_1.upk
del contents\bns\CookedPC\Suwal_4001_Federation_1_2.upk
del contents\bns\CookedPC\Suwal_4001_FederationInfo.upk
del contents\bns\CookedPC\Suwal_4002_Federation_0_0.upk
del contents\bns\CookedPC\Suwal_4002_Federation_0_1.upk
del contents\bns\CookedPC\Suwal_4002_Federation_0_2.upk
del contents\bns\CookedPC\Suwal_4002_Federation_1_0.upk
del contents\bns\CookedPC\Suwal_4002_Federation_1_1.upk
del contents\bns\CookedPC\Suwal_4002_Federation_1_2.upk
del contents\bns\CookedPC\Suwal_4002_Federation_2_1.upk
del contents\bns\CookedPC\Suwal_4002_FederationInfo.upk
del contents\bns\CookedPC\Suwal_4003_Federation_0_0.upk
del contents\bns\CookedPC\Suwal_4003_Federation_0_1.upk
del contents\bns\CookedPC\Suwal_4003_Federation_1_0.upk
del contents\bns\CookedPC\Suwal_4003_Federation_1_1.upk
del contents\bns\CookedPC\Suwal_4003_Federation_2_0.upk
del contents\bns\CookedPC\Suwal_4003_FederationInfo.upk
del contents\bns\CookedPC\Suwal_4004_Federation_0_0.upk
del contents\bns\CookedPC\Suwal_4004_Federation_0_1.upk
del contents\bns\CookedPC\Suwal_4004_Federation_0_2.upk
del contents\bns\CookedPC\Suwal_4004_Federation_1_0.upk
del contents\bns\CookedPC\Suwal_4004_Federation_1_1.upk
del contents\bns\CookedPC\Suwal_4004_Federation_1_2.upk
del contents\bns\CookedPC\Suwal_4004_Federation_2_0.upk
del contents\bns\CookedPC\Suwal_4004_Federation_2_1.upk
del contents\bns\CookedPC\Suwal_4004_FederationInfo.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00006160.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00007910.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00008762.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00009805.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00009812.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00010057.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00010358.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00010628.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00010772.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00011416.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00012537.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00012592.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00013419.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00015076.upk
del contents\Local\NCWEST\ENGLISH\CookedPC\00027224.upk
del contents\Local\NCWEST\web\common\character\skin\1\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\2\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\3\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\4\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\5\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\6\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\7\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\8\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\9\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\10\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\11\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\12\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\13\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\14\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\15\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\16\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\17\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\18\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\19\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\20\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\21\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\22\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\23\icSearch.png
del contents\Local\NCWEST\web\common\character\skin\24\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\1\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\1\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\1\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\1\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\1\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\1\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\2\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\2\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\2\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\2\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\2\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\2\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\3\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\3\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\3\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\3\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\3\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\3\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\4\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\4\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\4\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\4\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\4\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\4\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\5\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\5\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\5\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\5\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\5\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\5\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\6\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\6\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\6\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\6\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\6\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\6\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\7\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\7\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\7\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\7\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\7\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\7\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\8\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\8\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\8\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\8\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\8\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\8\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\9\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\9\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\9\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\9\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\9\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\9\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\10\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\10\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\10\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\10\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\10\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\10\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\11\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\11\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\11\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\11\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\11\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\11\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\12\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\12\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\12\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\12\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\12\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\12\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\13\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\13\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\13\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\13\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\13\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\13\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\14\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\14\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\14\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\14\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\14\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\14\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\15\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\15\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\15\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\15\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\15\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\15\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\16\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\16\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\16\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\16\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\16\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\16\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\17\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\17\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\17\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\17\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\17\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\17\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\18\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\18\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\18\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\18\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\18\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\18\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\19\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\19\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\19\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\19\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\19\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\19\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\20\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\20\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\20\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\20\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\20\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\20\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\21\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\21\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\21\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\21\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\21\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\21\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\22\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\22\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\22\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\22\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\22\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\22\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\23\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\23\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\23\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\23\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\23\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\23\icSearch.png
del contents\Local\NCWEST\web\common\market\skin\24\bgBuy.png
del contents\Local\NCWEST\web\common\market\skin\24\bgSellRegister.png
del contents\Local\NCWEST\web\common\market\skin\24\bgTableTh.png
del contents\Local\NCWEST\web\common\market\skin\24\btnBtns.png
del contents\Local\NCWEST\web\common\market\skin\24\icLayer.png
del contents\Local\NCWEST\web\common\market\skin\24\icSearch.png
PAUSE